### ISSUE TITLE
Bug related to Add widgets

### ISSUE THREAD

**Issue by sgoyalsmvj** [microsoft/devhome#2134]
### Dev Home version

0.901.374.0

### Windows build number

10.0.22631.3007

### Other software

OS Build Version: 10.0.22631.3007.amd64fre.ni_release.220506-1250
.NET Version: .NET 6.0.25

### Steps to reproduce the bug

I clicked on add widget button then a modal pop out but its empty I thought it may be due to I haven't add any widgets but the problem is  it doesn't get closed when I clicked the cross button.

### Expected result

The modal should  get closed

### Actual result

But It remained open and it freezes then I have to close the whole app.

### Included System Information

CPU: 12th Gen Intel(R) Core(TM) i5-1235U
Physical Memory: 15.71GB (4.49GB free)
Processor Architecture: x64

### Included Extensions Information

Extensions: 
Microsoft.Windows.DevHomeGitHubExtension_0.900.374.0_x64__8wekyb3d8bbwe
Microsoft.Windows.DevHome_0.901.374.0_x64__8wekyb3d8bbwe
9932MartCliment.WingetUIWidgets_0.3.0.0_x64__g91dtg5srk15g

Widget Service: 
MicrosoftWindows.Client.WebExperience_423.30700.0.0_x64__cw5n1h2txyewy

**Comment by vineeththomasalex** [comment]
@sgoyalsmvj Does the <esc> key work to close the popup?

**Comment by sgoyalsmvj** [comment]
Yes, the key to close the pop up is working now.
But the different widgets keep loading even they are Dev Home Widgets like CPU, GPU, etc.
Should I send the log files?
________________________________

**Comment by krschau** [comment]
@sgoyalsmvj The close button issue is tracked by #537.
In Dev Home version 0.901 (the one you have), if it's the first time you've opened Dev Home, we pin three Dev Home widgets for you automatically. If you don't want them, you can remove them (via the "..." button) and they should not be pinned automatically again. When you say "the different widgets keep loading" are you referring to these three widgets, or do widgets get pinned even if you press 'esc' to get out of the popup?

**Comment by sgoyalsmvj** [comment]
Yes, the close Button is working fine after that resolution.
By "the different widgets keep loading", I meant to say that when I click on the "Add widget" Button, then in the pop-up in the sidebar, you can see options for selecting widgets. When I choose any widget there, it doesn't show the widget; instead, the panel keeps loading.
But that is now also resolved by you. And it is working fine currently.
________________________________

**Comment by krschau** [comment]
Glad to hear things are working now. I'm going to close this issue since we still have the one open for the X button issue.
